#!/usr/bin/env python
import json, urllib2, sys, subprocess, os, random
FNULL = open(os.devnull, 'w')
base = 'http://dynamic.xkcd.com/api-0/jsonp/comic/'
def loadComicData(a=""):
	h = urllib2.urlopen(base+arg)
	s = h.read()
	h.close()
	j = json.loads(s)
	return j
arg = ""
if len(sys.argv)>1:
	arg = sys.argv[1]
if arg == 'r':
	j = loadComicData()
	arg = random.randrange(1,j["num"])
	if arg == 404:
		arg+=1
	arg = str(arg)
j = loadComicData(arg)
t = str(j["num"])+": "+j["title"]
subprocess.Popen(["display", "-title", t, j["img"]])
subprocess.Popen(["zenity", "--notification", "--text="+j["alt"]], stdout=FNULL, stderr=subprocess.STDOUT)
print t
print
print j["transcript"]
